### ISSUE TITLE
Uses the same variable name over and over.

### ISSUE THREAD

**Issue by benderTheCrime** [treycordova/nativejsx#4]
It looks like the compiler is outputting the same variable name over and over again:
```
    return function () {
        var $$a = document.createElement('div');
        // ...
        var $$a = document.createElement('select');
        $$a.appendChild($$a);
        return $$a;
    }();
```

**Comment by benderTheCrime** [comment]
I looked at the code for allocator, it seems to be doing what it should be. Perhaps there is an issue somewhere else in the middle?

**Comment by benderTheCrime** [comment]
This seems to be the culprit:
https://github.com/treycordova/nativejsx/blob/master/source/walkers.js#L109

Commenting it out, the code works fine

**Comment by treycordova** [comment]
Really, there was an incorrect assumption that a single `allocator` can be used across all closures and reset per closure. In reality, each closure requires a unique `allocator`, otherwise the variable naming will be wiped for subsequent allocations in the closure preceding it.

Or we allow a global `allocator` that resets when the _entire_ file is finished. I think that sounds more ideal and easier to follow from a debugging standpoint (variable shadowing is awfully confusing).

Nice catch, @benderTheCrime. I'll get out a fix immediately.

**Comment by benderTheCrime** [comment]
awesome, @treycordova, thanks :+1:

**Comment by treycordova** [comment]
I've released https://github.com/treycordova/nativejsx/releases/tag/3.0.2 with the fix in place. From my observations, it seems to be working. I'll continue to poke around just to be sure.

**Comment by treycordova** [comment]
Seems like all is well. Going to close this!
